### ISSUE TITLE
Socket timeout has expired [url=https://vault.bitwarden.com/identity/connect/token, socket_timeout=unknown] ms

### ISSUE THREAD

**Issue by kandilidinesh** [AChep/keyguard-app#653] opened 2024-10-18 15:53 UTC
I am getting this since yesterday while logging in to Bitwarden Account. I have bought the subscription on Google Play. Please provide resolution for this. 

Socket timeout has expired [url=https://vault.bitwarden.com/identity/connect/token, socket_timeout=unknown] ms

**Comment by AChep** [comment] 2024-10-18 15:57
Duplicate of #643

**Comment by AChep** [comment] 2024-10-18 15:58
The Play store version update is currently in review

**Closed** 2024-10-18 15:57 UTC
