### ISSUE TITLE
Misaligned text in edit window

### ISSUE THREAD

**Issue by NikunjKhangwal** [AChep/keyguard-app#237] opened 2024-03-30 15:50 UTC
Look at the text overlap
![IMG_20240330_211928](https://github.com/AChep/keyguard-app/assets/99175083/2427baca-a84e-4bab-8103-c630aebfe42b)

**Comment by AChep** [comment] 2024-03-30 15:53
Duplicate of #236

**Closed** 2024-03-30 15:54 UTC
