### ISSUE TITLE
Will Keyguard ever receive a Chrome extension?

### ISSUE THREAD

**Issue by dongltron** [AChep/keyguard-app#286] opened 2024-04-19 03:28 UTC
Would love to move away from the Bitwarden client entirely if possible, the only other time I have to use it is via Chrome. I know the Windows application is available, but the Chrome extension is obviously the fastest way to autofill. Was just wondering if that's in the works or even in consideration?

**Comment by AChep** [comment] 2024-04-19 03:44
Duplicate of #69

**Closed** 2024-04-19 03:45 UTC
