### ISSUE TITLE
无法添加账号

### ISSUE THREAD

**Issue by a1234321** [AChep/keyguard-app#644] opened 2024-10-17 10:15 UTC
![Screenshot_2024-10-17-18-15-01-89_f2500aab0c419d0d79426db9ab76c5a4.jpg](https://github.com/user-attachments/assets/4840c038-8005-4e8d-b7c2-7e8d67ea62e9)

**Comment by AChep** [comment] 2024-10-17 10:41
Duplicate of #643

**Closed** 2024-10-17 10:41 UTC
