### ISSUE TITLE
Use draw over for better support

### ISSUE THREAD

**Issue by pabloscloud** [AChep/keyguard-app#299] opened 2024-05-01 14:38 UTC
Some apps don't support the use of the accessibility service (or sth else?) so I often need to copy and paste credentials.

It would be a welcomed addition to implement draw-over functionality to support more apps :)

**Comment by AChep** [comment] 2024-05-01 15:20
While it would be nice to have, it's a huge pain to implement and a hacky way to implement autofill overall.

**Comment by AChep** [comment] 2024-05-01 15:21
Duplicate of #98

**Closed by AChep** 2024-05-01 15:20 UTC
