### ISSUE TITLE
F Droid Package Request

### ISSUE THREAD

**Issue by CompeyDev** [AChep/keyguard-app#191] opened 2024-03-02 11:42 UTC
Currently keyguard is only available on Play Store, which isn't the most privacy concious or open source platform. 

I request you to file a packaging request for F Droid, which is a more preferred app store for open source projects like keyguard.

**Comment by AChep** [comment] 2024-03-02 11:45
Duplicate of https://github.com/AChep/keyguard-app/issues/78

**Closed** 2024-03-02 11:45 UTC

**Comment by CompeyDev** [comment] 2024-03-02 11:49
My bad, I searched for "F Droid" and didn't find the issue. Sorry.

**Comment by CompeyDev** [comment] 2024-03-02 11:49
My bad, I searched for "F Droid" and didn't find the issue. Sorry.
