### ISSUE TITLE
Can not log in: Username or password is incorrect. Try again.

### ISSUE THREAD

**Issue by A3148475824** [AChep/keyguard-app#324] opened 2024-05-05 04:44 UTC
Whether using a proxy tool or a different device to log in will not work
Shows "" Username or password is incorrect. Try again.

**Comment by AChep** [comment] 2024-05-05 05:32
Which build ref is your version at? This should be addressed in the latest build.

**Comment by A3148475824** [comment] 2024-05-05 06:54
> Which build ref is your version at? This should be addressed in the latest build.您的版本在哪个版本参考？这应该在最新版本中解决。

Between this version and the previous version is not working, I went to register two accounts, found that I can not log in
And then I have three Android devices that don't work! I tried to use different proxy tools and different nodes,Unsuccessful

**Comment by AChep** [comment] 2024-05-05 07:52
Seems that that is now caused by Cloudflare's bot detection network. I'm looking into possible ways to fix it.

**Comment by parzival-cmd** [comment] 2024-05-05 10:47
Same issue here, first it was sync issue and then login issue now.

![Screenshot_20240505-161501.png](https://github.com/AChep/keyguard-app/assets/55645257/cbb4074e-eae8-4aba-87be-e5140d87591a)

**Comment by Subbarao6338** [comment] 2024-05-05 13:21
Same problem here

**Comment by frederikbeimgraben** [comment] 2024-05-05 14:17
Same here. Doesn't work since today.

**Comment by ngocanhtve** [comment] 2024-05-05 14:27
I also just encountered this issue

**Comment by parzival-cmd** [comment] 2024-05-05 14:30
Guys, it's fixed in the latest update.

https://github.com/AChep/keyguard-app/releases/tag/r20240505.3

**Comment by AChep** [comment] 2024-05-05 14:45
Fixed by switching from using Chrome to using Bitwarden's desktop app's device type and name. Hopefully it won't also get blocked by firewall rules eventually.

**Comment by parzival-cmd** [comment] 2024-05-05 14:52
> Fixed by switching from using Chrome to using Bitwarden's desktop app's device type and name. Hopefully it won't also get blocked by firewall rules eventually.
> 
> The update should be available on Google Play Store in few hours, 

Good going, Many thanks. I literally finally changed my password and email of bitwarden which I was actually planning to.

**Comment by kra-mo** [comment] 2024-06-03 14:00
I'm still getting the issue on desktop.

**Comment by yorukot** [comment] 2024-06-06 02:39
I think this issue still exists on the desktop...

**Comment by blue-duty** [comment] 2024-06-12 06:04
Why am I using a VPN and still not solving the problem?

**Comment by blue-duty** [comment] 2024-06-12 06:11
Do you mean I need to try another node?

**Comment by iAmSaugata** [comment] 2024-06-28 14:57
![image](https://github.com/AChep/keyguard-app/assets/26755120/d71117a5-cbae-4e7b-82db-df24822e9baa)
 Still having this issue on latest version

**Comment by ngocanhtve** [comment] 2024-06-28 15:47
> ￼
> 
> Still having this issue on latest version

I can't log in at all on macOS all the time

**Comment by AChep** [comment] 2024-06-28 16:01
Yeah, will adjust the User agent tomorrow to match what the Bitwarden sends. Hopefully it will solve the issue.

**Comment by AChep** [comment] 2024-06-30 17:58
Looks like it was caused by OkHttp using default platform's TLS provider, switching to Conscrypt on desktop platforms fixed the issue.

**Closed by AChep** 2024-06-30 17:58 UTC
Labels: bug

**Comment by leewp14** [comment] 2024-07-02 17:45
Just downloaded the latest Android release from github, but can't get it to login. Tried different IP but still same >.<

**Comment by AChep** [comment] 2024-07-02 18:26
> Just downloaded the latest Android release from github, but can't get it to login. Tried different IP but still same >.< Edit: I just registered in EU site and it is able to login! Not sure why. US site still cannot login for me.

Which platform are you talking about?

**Comment by leewp14** [comment] 2024-07-02 18:43
> > Just downloaded the latest Android release from github, but can't get it to login. Tried different IP but still same >.< Edit: I just registered in EU site and it is able to login! Not sure why. US site still cannot login for me.
> 
> Which platform are you talking about?

Android, release 2024.07.01

**Comment by AChep** [comment] 2024-07-02 18:52
I'll create a new build this night with a fix.

**Comment by leewp14** [comment] 2024-07-03 00:46
> I'll create a new build this night with a fix.

Happy to report that it works now. Thank you!
May I know how to purchase the premium, or is there donation link? I can't seem to see any inside the app.

**Comment by AChep** [comment] 2024-07-03 05:06
> > I'll create a new build this night with a fix.
> 
> Happy to report that it works now. Thank you!
> May I know how to purchase the premium, or is there donation link? I can't seem to see any inside the app. 

At this moment it's only in the Google Play store build.

**Comment by ngocanhtve** [comment] 2024-07-03 06:24
It is now able to log in on macOS.
