### ISSUE TITLE
After newest update Lables on Edit Screen are not aligned correcty

### ISSUE THREAD

**Issue by celevra** [AChep/keyguard-app#239] opened 2024-03-30 20:29 UTC
Hi,

See the Screenshot

Regards
![Screenshot_20240330_212814_Keyguard](https://github.com/AChep/keyguard-app/assets/232437/788964dc-e630-4db7-b3a4-5c504d2f79b2)

**Comment by AChep** [comment] 2024-03-30 21:06
Duplicate of #236

**Closed** 2024-03-30 21:07 UTC

**Comment by AChep** [comment] 2024-03-30 21:08
So many people noticed this, haha 😅 Glad you guys reported it, this makes me think a lot of people worry about UI glitches
