### ISSUE TITLE
Feature request: finger print on windows

### ISSUE THREAD

**Issue by Cromoray** [AChep/keyguard-app#444] opened 2024-07-01 21:39 UTC
Is it possible to enable to unlock the application using the biometric data (finger print or more rare the face) on windows?
Thanks you for this beautifull client.

**Comment by AChep** [comment] 2024-07-09 17:41
Duplicate of https://github.com/AChep/keyguard-app/issues/413

**Closed by AChep** 2024-07-09 17:41 UTC
